name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install libpcaudio-dev libsonic-dev ronn kramdown
    - name: autoconf
      run: ./autogen.sh ; chmod -x INSTALL ; chmod -x m4/*.m4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: ls -l m4/ ; make check
    - name: make distcheck
      run: make distcheck
